apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-tutorial-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/Chaws465/tekton-tutorial.git
    - name: revision
      value: main